### PR TITLE
Adapt package to build in Jessie

### PR DESCRIPTION
**Pull request by Alukardd**
Signed-off-by: Alexey Mochkin <alukardd@alukardd.org>

### CODE REVIEW

**Comment by noxiouz** [comment]
Hi, @Alukardd   sorry right now I'm out of time look at this. 
I'm going to do it tomorrow. 
May be it's better to drop cdbs support at all and migrate to dh-python? lucid is not supported anymore.

**Comment by Alukardd** [comment]
Ok. But at this moment I get as result empty debian package. Will try to fix it...

**Comment by noxiouz** [comment]
@Alukardd it should be fixed via 0b1cb8a4d20284bf368dc2172eee2aecd598c698. Check, please

**Comment by Alukardd** [comment]
Sorry but, I can't clearly check your commit, I still need changelog modification, because GBP can't build package vs dash(minus) in version with native format in Debian Jessie.

But I think for backward compatability will be right to specify this dependency: ```python-central | dh-python```

**Comment by noxiouz** [comment]
> package vs dash(minus) in version with native format in Debian Jessie.

with or without?

> But I think for backward compatability will be right to specify this dependency: python-central | dh-python

AFAIK, it's all about lucid. I don't like it :) Am I wrong?

**Comment by Alukardd** [comment]
> with or without?

of course "with"
As for me — I prefer quilt format...

I don't use ubuntu at all. Only Debian Wheezy and Jessie. And when I wrote this dependency I read only apt-cache policy in these two distors, but did real checks only in Jessie.

**Comment by noxiouz** [comment]
Ok, I will add dash next time and further

**Comment by Alukardd** [comment]
ooops, how we decide to add dash?)
> GBP can't build package with dash(minus)

**can't**
You needn't to add dash.

**Comment by Alukardd** [comment]
Master branch was built successfully.

**Pull request closed without merging**
